dist: trusty

addons:
  chrome: stable
  firefox: latest

language: node_js

node_js:
  - 10

install:
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
  - curl -L -O "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz && chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
  - npm install

script:
  - npm test